version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: au.com.dius.pact.consumer:junit5
    versions:
    - 4.2.3
  - dependency-name: au.com.dius.pact.provider:junit5spring
    versions:
    - 4.2.3
  - dependency-name: au.com.dius.pact.provider:spring
    versions:
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: au.com.dius.pact.consumer:java8
    versions:
    - 4.1.19
  - dependency-name: au.com.dius.pact
    versions:
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.61.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.61.Final
    - 4.1.63.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.61.Final
    - 4.1.63.Final
  - dependency-name: uk.gov.hmcts.java
    versions:
    - 0.12.3
    - 0.12.4
    - 0.12.7
  - dependency-name: info.solidsoft.pitest
    versions:
    - 1.6.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.19
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.1
  - dependency-name: com.azure:azure-messaging-servicebus
    versions:
    - 7.1.0
  - dependency-name: org.flywaydb.flyway
    versions:
    - 7.7.1
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-contract-wiremock
    versions:
    - 3.0.2
  - dependency-name: com.sun.xml.bind:jaxb-osgi
    versions:
    - 3.0.0
  - dependency-name: org.codehaus.groovy:groovy-xml
    versions:
    - 3.0.7
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.4
    - 5.3.5
  - dependency-name: au.com.dius.pact.provider:junit5
    versions:
    - 4.2.1
    - 4.2.2
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
  - dependency-name: org.apache.logging.log4j:log4j-to-slf4j
    versions:
    - 2.14.0
    - 2.14.1
  - dependency-name: org.springframework.retry:spring-retry
    versions:
    - 1.3.1
  - dependency-name: io.rest-assured:rest-assured
    versions:
    - 4.3.3
  - dependency-name: org.apache.qpid:qpid-jms-client
    versions:
    - 0.56.0
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.29.Final
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 10.0.2
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.12
