version: '2.2'

services:
  rd-caseworker-ref-api-db:
    build:
      context: database
    image: hmcts/rd-caseworker-ref-api-db
    container_name: rd-caseworker-ref-api-db
    volumes:
      - rd-caseworker-ref-api-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-dbrdcaseworker}"
    ports:
      - 5457:5432
volumes:
  rd-caseworker-ref-api-volume:
