apiVersion: v2
appVersion: "1.0"
description: A Helm chart for rd-caseworker-ref-api
name: rd-caseworker-ref-api
home: https://github.com/hmcts/rd-caseworker-ref-api
version: 0.0.6
maintainers:
  - name: Reference Data Team
dependencies:
  - name: java
    version: 2.9.1
    repository: '@hmctspublic'
