java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_PORT: "{{ .Values.postgresql.postgresqlPort}}"
    CWRD_MQ_HOST: rd-servicebus-aat.servicebus.windows.net
    CWRD_MQ_USERNAME: SendAndListenSharedAccessKey
    CWRD_MQ_TOPIC_NAME: rd-caseworker-topic-aat
    CWRD_MQ_TRUST_ALL_CERTS: false
    CWRD_DATA_PER_MESSAGE: 50
    LAUNCH_DARKLY_ENV: "preview"
  postgresql:
    enabled: true
    postgresqlUsername: dbrdcaseworker
    postgresqlPassword: dbrdcaseworker
    postgresqlDatabase: dbrdcaseworker
    postgresqlPort: 5432
  keyVaults:
    rd:
      secrets:
        - ApplicationInsightsInstrumentationKey
        - caseworker-topic-primary-send-listen-shared-access-key
        - caseworker-ref-api-s2s-secret
        - LD-SDK-KEY