java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  secrets:
    CWRD_MQ_PASSWORD:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: primaryKey
    CWRD_MQ_HOST:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: namespaceName

  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_PORT: "{{ .Values.postgresql.auth.port}}"
    CWRD_MQ_HOST: "$(CWRD_MQ_HOST).servicebus.windows.net"
    CASEWORKER_TOPIC_PRIMARY_SEND_LISTEN_SHARED_ACCESS_KEY: "$(CWRD_MQ_PASSWORD)"
    CWRD_MQ_USERNAME: RootManageSharedAccessKey
    CWRD_MQ_TOPIC_NAME: crd-aks-topic
    CWRD_MQ_TRUST_ALL_CERTS: false
    CWRD_DATA_PER_MESSAGE: 50
    LAUNCH_DARKLY_ENV: "preview"
    ENVIRONMENT_NAME: "preview"
    S2S_URL: http://rpe-service-auth-provider-demo.service.core-compute-demo.internal
    IDAM_URL: https://idam-api.demo.platform.hmcts.net
    USER_PROFILE_URL: http://rd-user-profile-api-demo.service.core-compute-demo.internal
    LOCATION_REF_DATA_URL: http://rd-location-ref-api-demo.service.core-compute-demo.internal
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-demo.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.demo.platform.hmcts.net/o
  postgresql:
    enabled: true
    auth:
      username: dbrdcaseworker
      password: dbrdcaseworker
      database: dbrdcaseworker
      port: 5432
  keyVaults:
    rd:
      secrets:
        - name: ApplicationInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: caseworker-ref-api-s2s-secret
          alias: CASEWORKER_REF_API_S2S_SECRET
        - name: LD-SDK-KEY
          alias: LD_SDK_KEY

servicebus:
  enabled: true
  teamName: RD
  resourceGroup: rd-aks
  serviceplan: standard
  setup:
    topics:
      - name: crd-aks-topic
        subscriptionNeeded: yes
