CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_skill_service_id ON dbrdcaseworker.skill(serviceId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_name ON dbrdcaseworker.case_worker_profile (LOWER(firstName), LOWER(lastName));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_user_type ON dbrdcaseworker.case_worker_profile(userTypeId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_work_area ON dbrdcaseworker.case_worker_work_area(caseWorkerId, serviceCode);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_role ON dbrdcaseworker.case_worker_role(caseWorkerId, roleId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_location ON dbrdcaseworker.case_worker_location(caseWorkerId, locationId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_skill ON dbrdcaseworker.case_worker_skill(caseWorkerId, skillId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_epimms_id ON dbrdcaseworker.building_location(epimmsId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_name ON dbrdcaseworker.building_location(UPPER(buildingLocationName));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_status ON dbrdcaseworker.building_location(UPPER(buildingLocationStatus));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_cluster_id ON dbrdcaseworker.building_location(clusterId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_region_id ON dbrdcaseworker.building_location(regionId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_venue_epimms_id ON dbrdcaseworker.court_venue(epimmsId);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_name ON dbrdcaseworker.court_venue(UPPER(courtName));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_site_name ON dbrdcaseworker.court_venue(UPPER(siteName));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_postcode ON dbrdcaseworker.court_venue(UPPER(postcode));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_address ON dbrdcaseworker.court_venue(UPPER(courtAddress));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_type_status ON dbrdcaseworker.court_venue (courtTypeId, courtStatus);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epimms_court_type_status ON dbrdcaseworker.court_venue (epimmsId, courtTypeId, courtStatus);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_region_status ON dbrdcaseworker.court_venue (regionId, courtStatus);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_building_name ON dbrdcaseworker.building_location (UPPER(buildingLocationName));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_status_open ON dbrdcaseworker.building_location (buildingLocationStatus);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cluster_id ON dbrdcaseworker.building_location (clusterId);