CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_skill_service_id ON dbrdcaseworker.skill(service_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_name ON dbrdcaseworker.case_worker_profile (LOWER(first_name), LOWER(last_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_user_type ON dbrdcaseworker.case_worker_profile(user_type_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_work_area ON dbrdcaseworker.case_worker_work_area(case_worker_id, service_code);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_role ON dbrdcaseworker.case_worker_role(case_worker_id, role_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_location ON dbrdcaseworker.case_worker_location(case_worker_id, location_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_case_worker_skill ON dbrdcaseworker.case_worker_skill(case_worker_id, skill_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_epimms_id ON dbrdcaseworker.building_location(epimms_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_name ON dbrdcaseworker.building_location(UPPER(building_location_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_status ON dbrdcaseworker.building_location(UPPER(building_location_status));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_cluster_id ON dbrdcaseworker.building_location(cluster_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_building_location_region_id ON dbrdcaseworker.building_location(region_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_venue_epimms_id ON dbrdcaseworker.court_venue(epimms_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_name ON dbrdcaseworker.court_venue(UPPER(court_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_site_name ON dbrdcaseworker.court_venue(UPPER(site_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_postcode ON dbrdcaseworker.court_venue(UPPER(postcode));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_court_address ON dbrdcaseworker.court_venue(UPPER(court_address));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_court_type_status ON dbrdcaseworker.court_venue (court_type_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_epimms_court_type_status ON dbrdcaseworker.court_venue (epimms_id, court_type_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_region_status ON dbrdcaseworker.court_venue (region_id, court_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_upper_building_name ON dbrdcaseworker.building_location (UPPER(building_location_name));
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_status_open ON dbrdcaseworker.building_location (building_location_status);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_cluster_id ON dbrdcaseworker.building_location (cluster_id);