INSERT INTO SKILL(skill_id,skill_code,description,service_id,user_type,created_date,last_update) VALUES
	 (46,'SKILL:ABA6:ProbateExamining','Probate Examining','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (47,'SKILL:ABA6:ProbateQA','Probate QA','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (48,'SKILL:ABA6:IntestacyExamining','Intestacy Examining','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (49,'SKILL:ABA6:IntestacyQA','Intestacy QA','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (50,'SKILL:ABA6:AdmonExamining','Admon Examining','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (51,'SKILL:ABA6:AdmonQA','Admon QA','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (52,'SKILL:ABA6:AdColligendaBonaQA','Ad Colligenda Bona QA','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (53,'SKILL:ABA6:AdColligendaBonaExamining','Ad Colligenda Bona Examining','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (54,'SKILL:ABA6:ProveForeignWill','Prove Foreign Will','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (55,'SKILL:ABA6:RectifyWillOrCodicil','Rectify Will Or Codicil','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (56,'SKILL:ABA6:CodicilMisRecital','Codicil MisRecital','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (57,'SKILL:ABA6:DeBonisNon','De Bonis Non','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (58,'SKILL:ABA6:DoubleProbate','Double Probate','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (59,'SKILL:ABA6:ExtendedIntestacy','Extended Intestacy','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (60,'SKILL:ABA6:FiatWill','Fiat Will','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (61,'SKILL:ABA6:ForeignDomicile','Foreign Domicile','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (62,'SKILL:ABA6:IncapacityUnder_Rule35','Incapacity Under Rule 35','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (63,'SKILL:ABA6:LeadingFollowingGrants','Leading FollowingGrants','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (64,'SKILL:ABA6:LiteraryEstate','Literary Estate','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (65,'SKILL:ABA6:LostWillCodicil','Lost Will Codicil','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (66,'SKILL:ABA6:MinorityInterest','Minority Interest','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (67,'SKILL:ABA6:PowerOfAttorney','Power Of Attorney','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (68,'SKILL:ABA6:ResealForeignGrant','Reseal Foreign Grant','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (69,'SKILL:ABA6:Section116','Section 116','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (70,'SKILL:ABA6:TrustCorporation','Trust Corporation','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (71,'SKILL:ABA6:WillOrCodicilToBeNotated','Will Or Codicil To Be Notated','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (72,'SKILL:ABA6:WitnessInterview','Witness Interview','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (73,'SKILL:ABA6:ProbateSME','Probate SME','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (74,'SKILL:ABA6:HorizonScheme','Horizon Scheme','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (75,'SKILL:ABA6:InfectedBloodCompensationAuthority','Infected Blood Compensation Authority','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (76,'SKILL:ABA6:InfectedBloodInterimScheme','Infected Blood Interim Scheme','ABA6','CTSC',timezone('utc', now()),timezone('utc', now())),
	 (77,'SKILL:ABA6:WindrushScheme','Windrush Scheme','ABA6','CTSC',timezone('utc', now()),timezone('utc', now()));
